server:
  port: 10005
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  main:
      allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000