server:
    port: 10006
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  ##数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/dbyyms?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 1800000
        idleTimeout: 600000
  application:
      name: trade-core-service
  redis:
      database: 0
      #120.78.170.118
      host: 120.78.170.118
      port: 6379
      password: 123456
      lettuce:
        shutdown-timeout: 30000ms
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.seamwhole.servicetradecore.model
  mapper-locations: classpath:mapping/**/*Mapper.xml

#pagehelper分页工具
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#logging:
#  level:
#    com.tongzhu.user.mapper : debug

## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#小程序ID
wx:
  appId: wxddfffbfc4fd5cd2a
#小程序密钥
  secret: b7f1baa9e99cb98bc0f8d1372a807521
#商户号
  mchId: xxxxxx
#支付签名
  paySignKey: xxxxxxxxx
#交易类型
  tradeType: JSAPI
#证书名称，对应不同的商户号
  certName: /cert/apiclient_cert.p12
#支付回调地址
  notifyUrl: https://www.fly2you.cn/admin/url/api/notify
#获取code的请求地址
  getCode: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
#获取Web_access_tokenhttps的请求地址
  webAccessTokenhttps: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
#拉取用户信息的请求地址
  userMessage: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
#微信统一下单接口路径
  uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
#退款地址
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
#退款查询地址
  refundqueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
#微信查询订单状态
  orderquery: https://api.mch.weixin.qq.com/pay/orderquery
