eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: gateway-zuul
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
zuul:
  routes:
    api-trade-core:
      path: /api-trade/**
      serviceId: trade-core-service
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000


