eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.141.78.42
  client:
    serviceUrl:
      defaultZone: http://10.141.78.42:8761/eureka/
server:
  port: 9991
spring:
  application:
    name: tree-house-zuul
  redis:
    database: 4
    host: 10.141.78.42 #120.55.167.171
    port: 16379
    password: tongzhutreehousetime
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user
    api-friend:
      path: /api-friend/**
      serviceId: friend
    api-userGoods:
      path: /api-goods/**
      serviceId: user-goods
    api-treeHouse:
      path: /api-treeHouse/**
      serviceId: tree-house
    api-message:
      path: /api-message/**
      serviceId: message
    api-fishing:
      path: /api-fishing/**
      serviceId: fishing
    api-welfare:
      path: /api-welfare/**
      serviceId: welfare
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
user:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
friend:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
user-goods:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
tree-house:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
message:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
fishing:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
welfare:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
hystrix:
    #  command:
      #    default:
      #      execution:
      #        isolation:
      #          thread:
  #            timeoutInMilliseconds: 60000
  user:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  friend:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  user-goods:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  tree-house:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  message:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  fishing:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  welfare:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000

