eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: gateway-zuul
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-service
    api-userGoods:
      path: /api-goods/**
      serviceId: goods-service
    api-message:
      path: /api-message/**
      serviceId: message-service
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
user:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
user-goods:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
message:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    SocketTimeout: 60000
hystrix:
    #  command:
      #    default:
      #      execution:
      #        isolation:
      #          thread:
  #            timeoutInMilliseconds: 60000
  user:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  user-goods:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000
  message:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 60000

