server:
  port: 10008
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  application:
    name: web-admin
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  redis:
    database: 0
    host: 120.78.170.118
    port: 6379
    password: 123456
    lettuce:
      shutdown-timeout: 30000ms
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 0
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000